### ISSUE TITLE
Unable to start Meural Media Player after Installation

### ISSUE THREAD

**Issue by dgohuoba** [GuySie/ha-meural#54]
I've installed HA-Meural and completed the setup.   The media player never starts.

Here is the log:
======================

This error originated from a custom integration.

Logger: homeassistant.core
Source: custom_components/meural/pymeural.py:146
Integration: Meural (documentation, issues)
First occurred: 10:41:35 PM (5 occurrences)
Last logged: 10:54:06 PM

Error executing service: <ServiceCall media_player.turn_on (c:01GJ4GN7Z70WTPDW8CSCE7499N): entity_id=['media_player.meural']>
Error executing service: <ServiceCall media_player.turn_on (c:01GJ4GNXN65GR4PSB5R2BWFMNR): entity_id=['media_player.meural']>
Error executing service: <ServiceCall media_player.turn_on (c:01GJ4GVGVDT3G2TDXGTSNA24NB): entity_id=['media_player.meural']>
Error executing service: <ServiceCall media_player.turn_on (c:01GJ4GX9DS1MBB4E5EKGD38XAP): entity_id=['media_player.meural']>
Error executing service: <ServiceCall media_player.turn_on (c:01GJ4HC577X3HF6Q3FRA3SB49W): entity_id=['media_player.meural']>
Traceback (most recent call last):
  File "/config/custom_components/meural/pymeural.py", line 147, in request
    resp = await self.session.request(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1762, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1781, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 208, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 943, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/config/custom_components/meural/media_player.py", line 469, in async_turn_on
    await self.local_meural.send_key_resume()
  File "/config/custom_components/meural/pymeural.py", line 174, in send_key_resume
    return await self.request("get", f"control_command/resume")
  File "/config/custom_components/meural/pymeural.py", line 146, in request
    with async_timeout.timeout(10):
  File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 116, in __exit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

**Comment by GuySie** [comment]
@dgohuoba Oh, that's weird. Could you send me a debug log from a restart up to when the meural is done setting up? I'm not sure what's happening here yet.

**Comment by dgohuoba** [comment]
2022-11-18 06:30:39.250 WARNING (MainThread) [homeassistant.components.media_player] Setup of media_player platform meural is taking over 10 seconds.
2022-11-18 06:30:47.323 ERROR (MainThread) [custom_components.meural.media_player] Meural device meural: Setup. Error while contacting local device, aborting setup
Traceback (most recent call last):
File "/config/custom_components/meural/pymeural.py", line 147, in request
resp = await self.session.request(
File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
conn = await self._connector.connect(
File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
proto = await self._create_connection(req, traces, timeout)
File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection
_, proto = await self._create_direct_connection(req, traces, timeout)
File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
transp, proto = await self._wrap_create_connection(
File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
return await self._loop.create_connection(*args, **kwargs) # type: ignore[return-value] # noqa
File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
sock = await self._connect_sock(
File "/usr/local/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
await self.sock_connect(sock, address)
File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
return await fut
asyncio.exceptions.CancelledError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/config/custom_components/meural/media_player.py", line 175, in async_added_to_hass
localgalleries = await self.local_meural.send_get_galleries()
File "/config/custom_components/meural/pymeural.py", line 210, in send_get_galleries
return await self.request("get", f"get_galleries_json/")
File "/config/custom_components/meural/pymeural.py", line 146, in request
with async_timeout.timeout(10):
File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 116, in __exit__
self._do_exit(exc_type)
File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 212, in _do_exit
raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

**Comment by GuySie** [comment]
@dgohuoba Huh, that's different from what's happening in https://github.com/GuySie/ha-meural/issues/53 but it seems related as you're both suddenly getting this startup problem within days of each other.

Could you check 4 things for me:

1. Can you control the Meural from their mobile app? E.g. go back and forward between art?
2. If you go to the Meural web interface and log in: https://my.meural.netgear.com/ and then navigate to your canvas and its settings, can you tell me what the Canvas Software Version is? Can you check if the Local IP according to their web interface matches what you think the IP of your Canvas is?
3. Can you go to http://**(fill in the device's local IP here)**/remote in the browser and check if you get a remote control interface on your device?
4. What version of Home Assistant are you on?

**Comment by dgohuoba** [comment]
1. Yes. I can control the art through the mobile application
2. Canvas Software Version - 2.0.9
3. Yep. The IP address match in both locations
4. Got a timeout going through the URL. Never seen this before. Not sure what it does
5. Home Assistant 2022.11.2

**Comment by dgohuoba** [comment]
Correction on item 4. I was able to view the remote interface using the browser on mobile phone

**Comment by GuySie** [comment]
Hmmmm, that is very interesting on 4. That request timing out is what is causing the setup to abort. Can you check if it's consistently unreachable from your desktop? I wonder if Meural changed something to the way the web remote can be reached.

**Comment by dgohuoba** [comment]
Tried several times on desktop browser and it's unreachable.

**Comment by dgohuoba** [comment]
Just an update. I got this working. A few months ago, I purchased a new wifi router and connected the Meural canvas to the new network but my HA (hosted in a VM on my NAS) was still using the old network router. I reset the wifi setting on the canvas to use the old router and everything started working.  Appreciate the help.
